-- Q1. Total Sales by Region
-- Calculate the total sales generated by each region.
-- Display Region and Total Sales, ordered from highest to lowest sales.


-- Q2. Total Sales by Product
-- Calculate the total sales generated by each product.
-- Display Product and Total Sales, ordered from highest to lowest sales.


-- Q3. Product Sales Within Each Region
-- Calculate the total sales for every product within each region.
-- Display Region, Product, and Total Sales.


-- Q4. Top-Selling Product in Each Region
-- Find the highest-selling product within each region.
-- Display Region, Product, and Total Sales.


-- Q5. Product Contribution Within Each Region
-- Calculate the percentage of each region's total sales
-- contributed by each product.
-- Display Region, Product, Total Sales, and Regional Sales Percentage.
